"""empty message

Revision ID: b0fea94e54e2
Revises: e24073e455f7
Create Date: 2024-09-11 15:16:27.859345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fea94e54e2'
down_revision = 'e24073e455f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_day', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_day', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
